tasks:
  - init: sudo apt update
    command: |
        pyenv install 3.9.0 &&
        pyenv global 3.9.0 &&
        pip install -r requirements.txt
vscode:
  extensions:
    - ms-python.black-formatter
    - unifiedjs.vscode-mdx
    - whizkydee.material-palenight-theme
    - LaurentTreguier.vscode-simple-icons
