site_name: Dismake
site_url: https://dismake.pages.dev

extra_css:
  - css/index.css
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.path
    - toc.integrate
    # Header Announcement
    - header.autohide
    # Search
    - search.suggest
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference

