site_name: Dismake

theme:
  name: material
  font:
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  palette:
    - scheme: default
      primary: black
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    