name: Build Documention Site 

on:
  push:
    paths:
      - "guide/**"
    branches:
      - main
  pull_request:
    paths:
      - "guide/**"
    branches:
      - main 
      
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v3
      
    - name: "Build Site"
      run: |
           cd guide
           npm i
           npx next build
 
