name: Build Documention Site 

on:
  push:
    paths:
      - "docs/**"
    branches:
      - "*"
  pull:
    paths:
      - "docs/**"
    branches:
      - "*"
      
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout Code"
      uses: actions/checkout@v3
    - name: "Build Site"
      runs: cd docs && npm i && npx next build


