name: Build Docs Site

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - '*'
  pull_request:
    paths:
      - 'docs/**'
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docs site
        run: |
          cd docs && npm i
          npx next build
